name: MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.14'

    # Install Miniconda
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10.14

    # Install dependencies and MLflow
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env create -f MLProject/conda.yaml
        conda activate amazon_mlflow_env
        pip install mlflow

    # Run MLflow Project
    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        conda activate amazon_mlflow_env
        mlflow run MLProject/ -P dataset=amazon_preprocessed.csv --experiment-name Amazon_Rating_Prediction_Autolog

    # Archive MLflow artifacts
    - name: Archive MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push Docker image
    - name: Build and push Docker image
      shell: bash -l {0}
      run: |
        conda activate amazon_mlflow_env
        # Get the latest run ID from MLflow
        RUN_ID=$(mlflow runs list --experiment-name Amazon_Rating_Prediction_Autolog | grep "active" | awk '{print $2}' | head -n 1)
        # Build Docker image
        mlflow models build-docker -m mlruns/0/$RUN_ID/artifacts/random_forest_model -n ${{ secrets.DOCKERHUB_USERNAME }}/amazon-model:latest
        # Push to Docker Hub
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/amazon-model:latest